name = "print-plan"

[env.production]
name = "print-plan-production"

[build]
command = "npm ci && npm run build"
watch_paths = ["src/**/*.{js,jsx,ts,tsx,css}", "public/**/*"]

[build.upload]
dir = "dist"


